### ISSUE TITLE
Installation with python setup.py doesn't seem to work when moving directories after install 

### ISSUE THREAD

**Issue by olivertam** [mhammell-laboratory/ezBAMQC#4]
I installed version 0.6.4 onto a server (genomics), and set the --prefix to ~/software/BAMqc/inst. Although the BAMqc executable was placed correctly into the bin folder, it can't be run from the bin folder. However, the executable in the src folder runs correctly when I run it in that folder, but not if I run it in another folder. I have set the path and python path to the BAMqc local installation (the same settings I used when installing).
Here are the error messages:
Traceback (most recent call last):
  File "/localdata1/galaxy/software/BAMqc/0.6.4/src/BAMqc", line 37, in <module>
    so=ctypes.CDLL(in_local)
  File "/localdata1/galaxy/software/python/2.7.9/inst/lib/python2.7/ctypes/**init**.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: build/lib.linux-x86_64-2.7/htslib.so: cannot open shared object file: No such file or directory

The files that are in error are the shared object files (which are in the build/lib.linux-x86_64-2.7/ folder in src). Is that path hardcoded? Should they be installed into the python2.7 libraries folders?

Thanks

**Comment by molikd** [comment]
This is an artifact in the build process. BAMqc is looking for the htslib.so that should have been built and can't find it.  GCC would have linked the two, but only in place. There may be a way to make the link more dynamic.

**Comment by molikd** [comment]
if you look at mhammell-laboratory/bamqc#4 there are some replicated issues.
